#ifndef CWS_INTERNALS_COMMON_H
#define CWS_INTERNALS_COMMON_H

#define CONTENT_TYPE_MAX 64
#define HEADER_KEY_MAX 256
#define HEADER_VALUE_MAX 1024
#define CHUNK_SIZE 8192
#define HEADERS_BUFFER_SIZE 2048

#endif
